### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by ohenepee** [WebReflection/jsgtk#14]
I am in need of a lightweight GUI framework for my Node.js application, both NW.js and Electron are not options b'cos of RAM usage even on a bare minimum example as they are essentially browsers. Does anyone know the average RAM usage with any of the examples?

**Comment by WebReflection** [comment]
WebKit2GTK demo using jsgtk (or just GJS) run on a Raspberry Pi 0
https://www.youtube.com/watch?v=hCLhGqadv04

But to better answer you, I need to know your HW constrains

**Comment by ohenepee** [comment]
P4 2.6GHz 512MB RAM running Linux... I need to only use max of 256MB RAM

**Comment by WebReflection** [comment]
running Linux ... which one?

**Comment by ohenepee** [comment]
AntiX Linux 16.1

**Comment by WebReflection** [comment]
Anyway, you can use raw GJS if JSGTK is too heavy (suggested) avoiding WebKit2GTK and using just GTK+ bindings.

Alternatives: Qt

**Comment by ohenepee** [comment]
Thanks!

**Comment by WebReflection** [comment]
No problems
