### ISSUE TITLE
Doesn't work on GNOME 3.24

### ISSUE THREAD

**Issue by iBelieve** [WebReflection/jsgtk#6]
I'm on Arch Linux, running GNOME 3.22. Locally and with the Flatpak GNOME 3.22 runtime, JSGtk+ runs correctly and my app works fine. However, using the GNOME 3.24 runtime, JSGtk+ throws a couple of errors and fails to run my app:

```
Gjs-Message: JS WARNING: [/app/lib/jsgtk/jsgtk_modules/jsgtk/babel.js 26]: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

(gjs:4): Gjs-WARNING **: JS ERROR: TypeError: "Promise" is read-only
L@/app/lib/jsgtk/jsgtk_modules/jsgtk/promise.js:9:4150
@/app/lib/jsgtk/jsgtk_modules/jsgtk/promise.js:9:6137
@/app/lib/jsgtk/jsgtk_modules/jsgtk/promise.js:9:2
@/app/bin/jsgtk:119:17
@/app/bin/jsgtk:7:1

JS_EvaluateScript() failed
```

**Comment by WebReflection** [comment]
Why don't engines mind their business , specially when a flag is meant to suppress pointless warnings? TL;DR one is a GJS **bug** the other is due GJS engine update with native Promise which by spec should be possible to overwrite anyway. I'll try to fix it on my side regardless

**Comment by WebReflection** [comment]
mind trying the latest version ? at least the Promise error should've gone (sorry I'm not on 3.24 yet)

**Comment by iBelieve** [comment]
Thanks for the quick response and fix, that did the trick. The Promise error is gone and my app works now on 3.24.

**Comment by WebReflection** [comment]
out of curiosity, is the warning still around? That might need a GJS bug, thanks.

**Comment by iBelieve** [comment]
@WebReflection Yes, that warning is still there.

**Comment by WebReflection** [comment]
after investigating and talking with GJS chaps, it looks like that error is a curse that affected all Babel users since ever, disappeared from recent Firefox versions (48+) but still in GJS 'cause it uses an old version of moz.js (38.something)

I'm not sure I can do much to fix that in here, beside suggesting to use `--no-transform` to avoid runtime transpilation of classes too.
